# Generated by Django 3.0.7 on 2020-06-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Janre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Наименование жанра')),
                ('slug', models.SlugField(unique=True, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Тег')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Картинка')),
                ('header', models.CharField(db_index=True, max_length=150, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, db_index=True, max_length=200, verbose_name='Описание')),
                ('rating', models.CharField(max_length=5, verbose_name='Рейтинг')),
                ('date_published', models.DateField(verbose_name='Дата выхода')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('janre', models.ManyToManyField(blank=True, related_name='cards', to='cards.Janre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
                'ordering': ['header'],
            },
        ),
    ]
